service: menu-qr-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USERS_TABLE: MenuQrUsersTable-${opt:stage, 'dev'}
    NODE_ENV: ${opt:stage, 'dev'}
    DYNAMODB_ENDPOINT: http://localhost:8000
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:207567761860:table/MenuQrUsersTable-${opt:stage, 'dev'}"
        - "arn:aws:dynamodb:${self:provider.region}:207567761860:table/MenuQrUsersTable-${opt:stage, 'dev'}/index/categoryId-index"
    - Effect: "Allow"
      Action:
        - "execute-api:Invoke"
      Resource:
        - "arn:aws:execute-api:${self:provider.region}:207567761860:*/*"
        
functions:
  # Funciones de Registro y Login
  signup:
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
          cors: ${self:custom.corsConfigExtended}

  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: ${self:custom.corsConfigExtended}

  # Funciones de usuario
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user/{userId}
          method: get
          cors: ${self:custom.corsConfig}

  #updateUserProfile:
  #  handler: handler.updateUserProfile
  #  events:
  #    - http:
  #        path: user/{userId}
  #        method: put
  #        cors: ${self:custom.corsConfig}

  # Funciones de manejo del menú
  home:
    handler: handler.home
    events:
      - http:
          path: home
          method: get
          cors: ${self:custom.corsConfig}

  menu:
    handler: handler.menu
    events:
      - http:
          path: menu
          method: get
          cors: ${self:custom.corsConfig}

  viewMenu:
    handler: handler.viewMenu
    events:
      - http:
          path: view-menu/{userId}
          method: get
          cors: ${self:custom.corsPublic}

  # Update data
#  updateCategory:
#    handler: handler.updateCategory
#    events:
#      - http:
#          path: menu/category/{categoryId}
#          method: put
#          cors: ${self:custom.corsConfigExtended}

  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          path: menu/product/{productId}
          method: put
          cors: ${self:custom.corsConfigExtended}

  # Funciones de categorías
  createCategory:
    handler: handler.createCategory
    events:
      - http:
          path: menu/category
          method: post
          cors: ${self:custom.corsConfig}

  getCategories:
    handler: handler.getCategories
    events:
      - http:
          path: categories/{userId}
          method: get
          cors: ${self:custom.corsConfig}

  deleteCategory:
    handler: handler.deleteCategory
    events:
      - http:
          path: menu/category/{categoryId}
          method: delete
          cors: ${self:custom.corsConfig}

  # Funciones de productos
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: menu/category/{categoryId}/product
          method: post
          cors: ${self:custom.corsConfig}

  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          path: menu/category/{categoryId}/product/{productId}
          method: delete
          cors: ${self:custom.corsConfig}

# ----------

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuQrUsersTable-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: categoryId-index
            KeySchema:
              - AttributeName: categoryId
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'https://dljrvybt2jogj.cloudfront.net'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'Content-Type, Authorization'"
          "gatewayresponse.header.Access-Control-Allow-Methods": "'GET,POST,PUT,DELETE,OPTIONS'"
          "gatewayresponse.header.Access-Control-Allow-Credentials": "'true'"

        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

plugins:
  - serverless-offline

custom:
  defaultRegion: us-east-1

  corsConfig: # Configuración estándar CORS
    origin: 'https://dljrvybt2jogj.cloudfront.net'
    headers:
      - Content-Type
      - Authorization
    allowCredentials: true

  corsConfigExtended: # Configuración CORS extendida
    origin: 'https://dljrvybt2jogj.cloudfront.net'
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowCredentials: true

  corsPublic: # Configuración CORS para rutas públicas
    origin: '*'
    headers:
      - Content-Type
    allowCredentials: false

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!.git/**'
    - '!.vscode/**'
    - '!tests/**'
    - '!.env*'
    - '!docs/**'
    - '!*.md'
    - '!**/*.ts'
    - '!**/*.d.ts'
    - '!node_modules/aws-sdk/**'
    - '!node_modules/.bin/**'
    - '!.serverless/**'
    - '!package-lock.json'